// <auto-generated />
using System;
using CodeZone.Attendance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeZone.Attendance.Data.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    partial class AttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 2
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 2
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 2
                        },
                        new
                        {
                            Id = 103,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 104,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 105,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 106,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 107,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 2
                        },
                        new
                        {
                            Id = 108,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 109,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 110,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 111,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 112,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Status = 2
                        },
                        new
                        {
                            Id = 113,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 114,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 115,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 116,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 117,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 118,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 119,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 120,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 121,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 122,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 123,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 124,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 125,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 126,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Status = 1
                        },
                        new
                        {
                            Id = 127,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 128,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 129,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 130,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 131,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 132,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 133,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 134,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 135,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 136,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 137,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 138,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 139,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 140,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = 141,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 2
                        },
                        new
                        {
                            Id = 142,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 143,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 144,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 145,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 146,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 2
                        },
                        new
                        {
                            Id = 147,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 148,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 149,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 150,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 151,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 2
                        },
                        new
                        {
                            Id = 152,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 153,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 154,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 11,
                            Status = 1
                        },
                        new
                        {
                            Id = 155,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 156,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 157,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 158,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 159,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 160,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 161,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 162,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 163,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 164,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 165,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 166,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 167,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 168,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Status = 1
                        },
                        new
                        {
                            Id = 169,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 170,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 171,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 172,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 173,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 174,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 175,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 176,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 177,
                            Date = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 178,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 179,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 180,
                            Date = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 181,
                            Date = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 182,
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 13,
                            Status = 1
                        });
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ENG",
                            Location = "Building A, Floor 3",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HR",
                            Location = "Building B, Floor 1",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SAL",
                            Location = "Building A, Floor 2",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MKT",
                            Location = "Building C, Floor 2",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FIN",
                            Location = "Building B, Floor 2",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.smith@codezone.com",
                            FullName = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "sarah.johnson@codezone.com",
                            FullName = "Sarah Johnson"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "michael.brown@codezone.com",
                            FullName = "Michael Brown"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "emily.davis@codezone.com",
                            FullName = "Emily Davis"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Email = "david.wilson@codezone.com",
                            FullName = "David Wilson"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "jennifer.martinez@codezone.com",
                            FullName = "Jennifer Martinez"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Email = "robert.anderson@codezone.com",
                            FullName = "Robert Anderson"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            Email = "lisa.taylor@codezone.com",
                            FullName = "Lisa Taylor"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            Email = "james.thomas@codezone.com",
                            FullName = "James Thomas"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 4,
                            Email = "mary.jackson@codezone.com",
                            FullName = "Mary Jackson"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 4,
                            Email = "chris.white@codezone.com",
                            FullName = "Christopher White"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 5,
                            Email = "patricia.harris@codezone.com",
                            FullName = "Patricia Harris"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 5,
                            Email = "daniel.martin@codezone.com",
                            FullName = "Daniel Martin"
                        });
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("CodeZone.Attendance.Data.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.Employee", b =>
                {
                    b.HasOne("CodeZone.Attendance.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CodeZone.Attendance.Data.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
